# Generated by Django 5.0.6 on 2024-07-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_dept_item_brand_remove_item_user_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
