# Generated by Django 5.0.6 on 2024-07-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('itemnum', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
            ],
        ),
    ]
