# Generated by Django 5.1 on 2024-09-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ItemList', models.CharField(max_length=500)),
                ('Date', models.CharField(max_length=20)),
            ],
        ),
    ]
