# Generated by Django 5.1 on 2024-09-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Price2',
            field=models.IntegerField(default=0),
        ),
    ]
