# Generated by Django 5.1 on 2024-09-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_trash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=500)),
                ('item', models.CharField(max_length=20)),
                ('Brand', models.CharField(max_length=20)),
                ('SerialNo', models.CharField(max_length=20)),
                ('Quantity', models.CharField(max_length=20)),
                ('Doctype', models.CharField(max_length=20)),
                ('Remark', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Trash',
        ),
    ]
