# Generated by Django 5.1 on 2024-09-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_item_price2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Price2',
        ),
    ]
