# Generated by Django 5.1 on 2024-09-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_documents_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='item',
        ),
        migrations.AddField(
            model_name='documents',
            name='items',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
