# Generated by Django 5.1 on 2024-11-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_documents_item_documents_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=30)),
                ('IDnumber', models.CharField(max_length=500)),
                ('AssertName', models.CharField(default='none', max_length=200)),
                ('SerialNumber', models.CharField(max_length=20)),
                ('Date', models.CharField(default='none', max_length=20)),
            ],
        ),
    ]
