# Generated by Django 5.1 on 2024-11-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_trash_contactnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trash',
            old_name='User',
            new_name='username',
        ),
    ]
