# Generated by Django 5.1 on 2024-11-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_brand_documents_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='./uploads/'),
        ),
    ]
