# Generated by Django 5.1 on 2024-11-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_documents_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='assertid',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
